services:
  isponsorblocktv:
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    container_name: isponsorblocktv
    env_file: .env
    volumes:
      - /mnt/app/isponsorblocktv/config:/app/data
    ports:
      - "8283:8283"
    restart: unless-stopped
