services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    network_mode: "container:gluetun"
    env_file:
      - .env
    volumes:
      - /mnt/app/qbittorrent/config:/config
      - /mnt/storage/mediadata/data:/data
    restart: unless-stopped