services:
  github-runner:
    build: .
    container_name: github-runner
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/app:/mnt/app
      - /var/run/middleware.sock:/var/run/middleware.sock
    restart: unless-stopped
