services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.5
    container_name: sabnzbd
    env_file:
      - .env
    volumes:
      - /mnt/storage/sabnzbd/config:/config
      - /mnt/storage/mediadata/data:/data
    ports:
      - 8085:8080
    restart: unless-stopped