services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:5.0.3
    container_name: sabnzbd
    env_file:
      - .env
    volumes:
      - /mnt/app/sabnzbd/config:/config
      - /mnt/storage/mediadata/data:/data
    ports:
      - 8085:8080
    labels:
      kuma.sabnzbd.http.name: "SABnzbd"
      kuma.sabnzbd.http.url: "https://sabnzbd.sebastianastalos.com"
    restart: unless-stopped