services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    env_file: .env
    depends_on:
      - paperless-db
      - paperless-redis
    volumes:
      - /mnt/app/paperless/data:/usr/src/paperless/data
      - /mnt/storage/paperless/media:/usr/src/paperless/media
      - /mnt/storage/paperless/export:/usr/src/paperless/export
      - /mnt/storage/paperless/consume:/usr/src/paperless/consume
    ports:
      - "8010:8000"
    labels:
      kuma.paperless.http.name: "Paperless"
      kuma.paperless.http.url: "https://paperless.sebastianastalos.com"
    restart: unless-stopped

  paperless-db:
    image: postgres:18
    container_name: paperless-db
    env_file: .env
    volumes:
      - /mnt/app/paperless/db:/var/lib/postgresql
    restart: unless-stopped

  paperless-redis:
    image: redis:8
    container_name: paperless-redis
    restart: unless-stopped
