services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0
    container_name: radarr
    env_file:
      - .env
    volumes:
      - /mnt/app/radarr/config:/config
      - /mnt/storage/mediadata/media:/media
      - /mnt/storage/mediadata/data:/data
    ports:
      - 7878:7878
    labels:
      kuma.radarr.http.name: "Radarr"
      kuma.radarr.http.url: "https://radarr.sebastianastalos.com"
    restart: unless-stopped