services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1
    container_name: radarr
    env_file:
      - .env
    volumes:
      - /mnt/storage/radarr/config:/config
      - /mnt/storage/mediadata/media:/media
      - /mnt/storage/mediadata/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped