services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    container_name: homepage
    env_file:
      - .env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${NAS_IP}:3000
    volumes:
      - /mnt/storage/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3000:3000
    restart: unless-stopped