services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    env_file:
      - .env
    volumes:
      - /mnt/storage/adguard/conf:/opt/adguardhome/conf
      - /mnt/storage/adguard/work:/opt/adguardhome/work
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 3001:3000
      - 8070:80
    restart: unless-stopped
