services:
  adguard:
    image: adguard/adguardhome:v0.107.78
    container_name: adguard
    network_mode: host
    env_file:
      - .env
    volumes:
      - /mnt/app/adguard/conf:/opt/adguardhome/conf
      - /mnt/app/adguard/work:/opt/adguardhome/work
    labels:
      kuma.adguard.http.name: "AdGuard Home"
      kuma.adguard.http.url: "https://adguard.sebastianastalos.com"
    restart: unless-stopped
