services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    network_mode: host
    env_file:
      - .env
    volumes:
      - /mnt/storage/adguard/conf:/opt/adguardhome/conf
      - /mnt/storage/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
