services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:v2.27.2
    container_name: aiostreams
    env_file:
      - .env
    volumes:
      - /mnt/app/aiostreams/config:/app/data
    ports:
      - 8081:3000
    restart: unless-stopped
