services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.8
    container_name: jellyfin
    env_file:
      - .env
    volumes:
      - /mnt/storage/jellyfin/config:/config
      - /mnt/storage/mediadata/media:/data/media
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "107"
    restart: unless-stopped