services:
  dozzle:
    image: amir20/dozzle:v10.6.11
    container_name: dozzle
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9999:8080"
    labels:
      kuma.dozzle.http.name: "Dozzle"
      kuma.dozzle.http.url: "https://dozzle.sebastianastalos.com"
    restart: unless-stopped



