services:
  seerr:
    image: ghcr.io/seerr-team/seerr:v3.2.0
    container_name: seerr
    init: true
    env_file:
      - .env
    volumes:
      - /mnt/app/seerr/config:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped