services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.6
    container_name: bazarr
    env_file:
      - .env
    volumes:
      - /mnt/storage/bazarr/config:/config
      - /mnt/storage/mediadata/media:/media
    ports:
      - 6767:6767
    restart: unless-stopped
