services:
  graphite-exporter:
    image: prom/graphite-exporter:v0.17.0
    container_name: graphite-exporter
    env_file: .env
    volumes:
      - /mnt/app/graphite-exporter/config/mappings.yml:/tmp/mappings.yml:ro
    command: --graphite.mapping-config=/tmp/mappings.yml
    ports:
      - "9109:9108"
      - "2003:9109"
      - "2003:9109/udp"
    restart: unless-stopped
