services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/app/gluetun/config:/gluetun
    env_file:
      - .env
    restart: unless-stopped

  tailscale-proton:
    image: tailscale/tailscale:v1.102.4
    container_name: tailscale-proton
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    volumes:
      - /mnt/app/gluetun/tailscale:/var/lib/tailscale
    restart: unless-stopped
