services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888
      - 8082:8082
      - 9696:9696
      - 8000:8000
    volumes:
      - /mnt/app/gluetun/config:/gluetun
    env_file:
      - .env
    restart: unless-stopped