services:
  promtail:
    image: grafana/promtail:3.6.11
    container_name: promtail
    user: root
    env_file: .env
    volumes:
      - /mnt/app/promtail/config/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/promtail.yml
    restart: unless-stopped
