name: Secrets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v5
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          PORKBUN_API_KEY: op://Homelab/porkbun API/API Key
          PORKBUN_SECRET_API_KEY: op://Homelab/porkbun API/Secret Key
          TS_AUTHKEY: op://Homelab/UGREEN Tailscale Auth Key/password
          TS_OAUTH_CLIENT_ID: op://Homelab/CI GitHub - Tailscale/Client ID
          TS_OAUTH_CLIENT_SECRET: op://Homelab/CI GitHub - Tailscale/Client Secret
          GITHUB_PAT: op://Homelab/GitHub PAT TrueNAS/password
          TRUENAS_API_KEY: op://Homelab/TrueNAS/API Key
